source 'https://rubygems.org'

gem 'rails', '~> 6.0.4.8'
gem 'public_suffix', '< 1.5.0'

gem 'impressionist', :path => '../../'

platforms :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'jdbc-sqlite3'
  gem 'jruby-openssl'
end

platforms :ruby, :mswin, :mingw do
  gem 'pg'
  gem 'sqlite3'
  gem 'bson_ext'
end

gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 6'
  gem 'coffee-rails', '~> 5.0'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 4.2.0'
end

group :development, :test do
  gem 'autotest-notification'
  gem 'rspec-rails', '~> 4.0.2'
  gem 'spork'

  # test/unit has been removed by default in Ruby 2.2.x+
  gem 'test-unit'
end

group :test do
  gem 'capybara'
  gem 'simplecov'
  gem 'systemu'
end

gem 'jquery-rails'
gem 'friendly_id', '~> 5.4.2'
